name: Packer CI Workflow

on:
  pull_request:
    branches:
      - main
        
jobs:
  build:
    name: Packer CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: latest
    
    - name: Create webapp.zip
      run: |
        zip -r webapp.zip . -x "*.git*" "node_modules/*"
  
    - name: Install plugins
      run: packer init .

    - name: Run packer fmt
      run: packer fmt .

    - name: Validate Packer template
      run: packer validate .