name: Packer CI Workflow

on:
  pull_request:
    branches:
      - main
env:
  PKR_VAR_ami_name: ${{ secrets.AMI_NAME }}
  PKR_VAR_ami_regions: ${{ secrets.AMI_REGIONS }}
  PKR_VAR_ami_description: ${{ secrets.AMI_DESCRIPTION }}
  PKR_VAR_source_ami: ${{ secrets.SOURCE_AMI }}
  PKR_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
  PKR_VAR_ssh_username: ${{ secrets.SSH_USERNAME }}
  PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
  PKR_VAR_region: ${{ secrets.REGION }}
  PKR_VAR_db_user: ${{ secrets.DB_USER }}
  PKR_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  PKR_VAR_db_name: ${{ secrets.DB_DATABASE }}
        
jobs:
  build:
    name: Packer CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: latest
    
    - name: Create webapp.zip
      run: |
        zip -r webapp.zip . -x "*.git*" "node_modules/*" "packer/aws.auto.pkrvars.hcl"
  
    - name: Install plugins
      run: packer init packer/aws.pkr.hcl

    - name: Run packer fmt
      run: packer fmt -check packer/aws.pkr.hcl

    - name: Validate Packer template
      run: packer validate packer/aws.pkr.hcl