name: Build Packer Image Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Packer Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update AWS CLI to the latest version
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update   # Add the --update flag to update the existing CLI
        aws --version  # Check the updated version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Build Artifact
      run: |
        npm install
        npm run build

    - name: Build Packer Image
      run: |
        packer build packer/aws.pkr.hcl

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-artifact
        path: dist/
