name: Packer Build Image Workflow

on:
  pull_request:
    branches:
      - main

env:
  PKR_VAR_ami_name: ${{ secrets.AMI_NAME }}
  PKR_VAR_ami_regions: ${{ secrets.AMI_REGIONS }}
  PKR_VAR_ami_description: ${{ secrets.AMI_DESCRIPTION }}
  PKR_VAR_source_ami: ${{ secrets.SOURCE_AMI }}
  PKR_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
  PKR_VAR_ssh_username: ${{ secrets.SSH_USERNAME }}
  PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
  PKR_VAR_region: ${{ secrets.REGION }}
  PKR_VAR_db_user: ${{ secrets.DB_USER }}
  PKR_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  PKR_VAR_db_name: ${{ secrets.DB_DATABASE }}
  PKR_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PKR_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.REGION }}     
jobs:
  build:
    name: Packer Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          touch .env

          cat .env

    - name: Zip folder
      run: zip -r webapp.zip . -x "*.git*" "node_modules/*" "packer/aws.auto.pkrvars.hcl"
    
    - name: Update AWS CLI to the latest version
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update   # Add the --update flag to update the existing CLI
        aws --version  # Check the updated version
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile dev
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile dev
        aws configure set region ${{ secrets.REGION }} --profile dev
        aws configure set output json --profile dev
        aws configure list --profile dev
    
    - name: Verify AWS Configuration
      run: |
        echo "Checking AWS credentials and config files"
          
        # Check AWS credentials file
        echo "AWS Credentials file:"
        cat ~/.aws/credentials
  
        # Check AWS config file
        echo "AWS Config file:"
        cat ~/.aws/config
  
        # Check AWS CLI configuration
        aws configure list --profile dev
  
        # Output the current working directory and location of credentials
        echo "Credentials and config files are located at ~/.aws/"
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Export AWS credentials for Packer
      run: |
        echo "Exporting AWS credentials for Packer"
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION=${{ secrets.REGION }}
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY
        echo $AWS_DEFAULT_REGION
        echo "AWS credentials exported successfully."
        export AWS_PROFILE=dev
        echo $AWS_PROFILE

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Initialize Packer
      run: |
        packer init packer/aws.pkr.hcl

    - name: Build Packer Image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        packer build packer/aws.pkr.hcl