name: Packer Build Image Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Packer Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip folder
      run: zip -r webapp.zip . -x "*.git*" "node_modules/*" "scripts/aws.auto.pkrvars.hcl"
    
    - name: Update AWS CLI to the latest version
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update   # Add the --update flag to update the existing CLI
        aws --version  # Check the updated version
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile demo
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile demo
        aws configure set region ${{ secrets.REGION }} --profile demo
        aws configure set output json --profile demo
        aws configure list --profile demo
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Export AWS credentials for Packer
      run: |
        echo "Exporting AWS credentials for Packer"
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION=${{ secrets.REGION }}

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2

    - name: Initialize Packer
      run: |
        packer init .

    - name: Build Packer Image
      run: |
          packer build \
            -var 'aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -var 'aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -var 'aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}' \
            -var 'db_host=${{ secrets.DB_HOST }}' \
            -var 'db_port=${{ secrets.DB_PORT }}' \
            -var 'db_user=${{ secrets.DB_USER }}' \
            -var 'db_password=${{ secrets.DB_PASSWORD }}' \
            -var 'db_database=${{ secrets.DB_DATABASE }}' \
            -var 'instance_type=${{ secrets.INSTANCE_TYPE }}' \
            -var 'ami_name=${{ secrets.AMI_NAME }}' \
            -var 'ami_description=${{ secrets.AMI_DESCRIPTION }}' \
            -var 'ami_regions=${{ secrets.AMI_REGIONS }}' \
            -var 'region=${{ secrets.REGION }}' \
            -var 'source_ami=${{ secrets.SOURCE_AMI }}' \
            -var 'subnet_id=${{ secrets.SUBNET_ID }}' \
            -var 'ssh_username=${{secrets.SSH_USERNAME}}'\
             aws.pkr.hcl