name: Packer CI Workflow

on:
  push:
    branches:
      - main
env:
  PKR_VAR_ami_name: ${{ secrets.AMI_NAME }}
  PKR_VAR_ami_regions: ${{ secrets.AMI_REGION }}
  PKR_VAR_ami_description: ${{ secrets.AMI_DESCRIPTION }}
  PKR_VAR_source_ami: ${{ secrets.SOURCE_AMI }}
  PKR_VAR_instance_type: ${{ secrets.INSTANCE_TYPE }}
  PKR_VAR_ssh_username: ${{ secrets.SSH_USERNAME }}
  PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
  PKR_VAR_region: ${{ secrets.REGION }}
  PKR_VAR_db_user: ${{ secrets.DB_USER }}
  PKR_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  PKR_VAR_db_name: ${{ secrets.DB_NAME }}
        
jobs:
  built:
    name: Packer CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: latest
    
    - name: Show env variables
      run: |
        echo $PKR_VAR_ami_name
        echo $PKR_VAR_ami_regions
        echo $PKR_VAR_ami_description
        echo $PKR_VAR_source_ami
        echo $PKR_VAR_instance_type
        echo $PKR_VAR_ssh_username
        echo $PKR_VAR_subnet_id
        echo $PKR_VAR_region
        echo $PKR_VAR_db_user
        echo $PKR_VAR_db_password
        echo $PKR_VAR_db_name
        echo $ami_name
        echo $ami_regions
        echo $ami_description
        echo $source_ami
        echo $instance_type
        echo $ssh_username
        echo $subnet_id
        echo $region
        echo $db_user
        echo $db_password
        echo $db_name

    - name: Install plugins
      run: packer init packer/aws.pkr.hcl

    - name: Run packer fmt
      run: packer fmt -check packer/aws.pkr.hcl

    - name: Validate Packer template
      run: packer validate packer/aws.pkr.hcl