name: Integaration Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Integration Test Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v3

      # Set up PostgreSQL
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql
          sudo psql --version

      # Set up PostgreSQL environment (create user, DB, and configure)
      - name: Setup PostgreSQL Database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_USER }};"
          sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH PASSWORD '${{ env.DB_PASSWORD }}';"
          sudo -u postgres psql -c "ALTER USER ${{ env.DB_USER }} CREATEDB;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DB_USER }} TO ${{ env.DB_USER }};"
          sudo -u postgres psql -c "ALTER SYSTEM SET listen_addresses = '*';"
        env:
          PGHOST: localhost
          PGUSER: ${{ env.DB_USER }}
          PGPASSWORD: ${{ env.DB_PASSWORD }}
          PGDATABASE: ${{ env.DB_DATABASE }}
          PGPORT: ${{ env.DB_PORT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm ci

      - name: "Check Environment Variables"
        run: echo ${{ env.DB_DATABASE }}

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: ${{ env.DB_USER }}
          PGPASSWORD: ${{ env.DB_PASSWORD }}
          PGDATABASE: ${{ env.DB_NAME }}
          PGPORT: 5432
        run: npm test
