name: Integaration Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    name: Integration Test Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to our code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test