name: Integaration Test Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Integration Test Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to our code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm test
