name: Integration Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Integration Test Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v3

      # Set up PostgreSQL
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo psql --version

      # Set up PostgreSQL environment (create user, DB, and configure)
      - name: Setup PostgreSQL Database
        run: |
          # Check if the role exists, create if not
          sudo -u postgres psql -c "DO \$$
          BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${{ secrets.DB_USER }}') THEN
              CREATE ROLE ${{ secrets.DB_USER }} WITH LOGIN PASSWORD '${{ secrets.DB_PASSWORD }}';
            END IF;
          END\$$;"
          
          # Check if the database exists and create it if it doesn't exist
          if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw ${{ secrets.DB_DATABASE }}; then
            sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_DATABASE }};"
          fi
          # Grant privileges
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DB_DATABASE }} TO ${{ secrets.DB_USER }};"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON SCHEMA public TO ${{ secrets.DB_USER }};"
          sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USER }} WITH SUPERUSER;"

        env:
          DB_HOST: localhost
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm install

      - name: "Check Environment Variables"
        run: echo ${{ secrets.DB_DATABASE }}
      
      - name: Drop conflicting schema if exists
        run: |
          sudo -u postgres psql -c "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;"
      
      - name: Restart PostgreSQL
        run: sudo systemctl restart postgresql
      
      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: 5432
        run: npm test
